
services:
  mihomo:
    image: izumiko/mihomo
    container_name: mihomo
    restart: unless-stopped
    ports:
      - "7890:7890"
      - "7891:7891"
      - "7892:7892"
      - "9090:9090"
    volumes:
      - ./mihome/config:/root/.config/mihomo
    # 如果需要后台运行，compose 默认就是 daemon 模式
  zashboard:
    image: ghcr.io/zephyruso/zashboard:latest
    container_name: zashboard
    restart: unless-stopped
    ports:
      - "3001:80"
